Uncertain ranges
biocommons/hgvs pull request #699
Opened 2023-09-20 16:29 UTC by theferrit32

2023-09-20 16:49 UTC, theferrit32 commented
Haven't added for `c.` yet. The `hgvs.pymeta` changes are likely similar but will need to add tests.

2023-11-09 15:26 UTC, korikuzma commented
@biocommons/hgvs-maintainers Would we be able to get feedback on this PR?

2023-12-11 16:25 UTC, andreasprlic commented on tests/test_hgvs_sequencevariant.py
> +        self.assertEqual(type(v.posedit.edit).__name__, "Dup")
Should this also test the uncertain field to make sure it is set correctly?

2023-12-11 16:27 UTC, andreasprlic commented
It would be great to get this PR in. Can we just make sure the "uncertain" field on BaseOffsetPosition or SimplePosition gets set correctly (and tested in the unit test)?

Thanks!

2023-12-11 23:52 UTC, andreasprlic commented on tests/test_hgvs_sequencevariant.py
> +        self.assertEqual(type(v.posedit.edit).__name__, "Dup")
Merged #713 in to unblock CI and added the tests I thought were missing

2023-12-11 23:54 UTC, andreasprlic approved these changes
LGTM

2023-12-12 07:53 UTC, andreasprlic commented
Playing around with this branch some more I realized that g_to_c projection was not yet working. As such I had a go at enabling this. Since the behavior of this projection is somewhat undefined, the current approach picks the inner (=confident) interval of the uncertain range and uses that for the .c projection. The resulting hgvs_c string is then "confident" and not "uncertain" any longer.

2024-02-10 01:50 UTC, andreasprlic commented
Can we work on this one on Monday during our dev session?

2024-02-15 00:22 UTC, andreasprlic commented
As discussed on Monday, here a screenshot of `NC_000009.11:g.108337304_108337428del`. If we would represent this as a closely related, but imprecise event `NC_000009.11:g.(?_108337304)_(108337428_?)del` , how would we like the hgvs_c to be?

Would we want g_to_c to resul in `NM_001079802.1:c.-10_105+10del` for both the precise as well as imprecise event? If we were to map this to `NM_001079802.1:c.(?_-10)_(105+10_?)del`, do we want this to be comparable with the precise form in some form?

<img width="1610" alt="Screenshot 2024-02-14 at 4 13 40 PM" src="https://github.com/biocommons/hgvs/assets/187599/bef6fe2e-7f7f-4eff-9e3d-a052214ea4af">

2024-02-18 21:16 UTC, reece commented
I believe that the c. uncertainty should match the g. uncertainty. That is, my preference is

`NC_000009.11:g.(?_108337304)_(108337428_?)del` ⇔ `NM_001079802.1:c.(?_-10)_(105+10_?)del`

In principle, I don't see any problem with a partially uncertain event, although I don't see how it would apply in this case.

2024-02-19 02:57 UTC, reece requested changes
An `x_interval` in this area of code is a definite (`def_`) interval or uncertain interval.
An uncertain interval is merely a definite interval in parentheses.
So, `def_g_uncertain_interval` doesn't make sense to me. What am I missing?

Also, if accepted, I think we'd want this interval form to apply to the other kinds of intervals.

2024-02-20 07:36 UTC, andreasprlic commented
Added imprecise hgvs_c strings, but it is not 100% there yet, since 

`NC_000009.11:g.(?_108337304)_(108337428_?)del` ⇔ `NM_001079802.1:c.(-10)_(105+10)del` at the moment. We want this to be `NM_001079802.1:c.(?_-10)_(105+10_?)del`. The problem is that the -10 comes out as a BaseOffsetPosition currently, when we prob would want it an Interval where the start has no "base" set. That prob. requires some more modifications on `g_to_n` in the alignmentmapper.

(see otherwise working cases in test_uncertain_projection_confidence)

2024-02-20 17:18 UTC, reece commented
Thanks for working this issue, Andreas.

I converted this PR to a draft to make it clear that it was a WIP.

2024-02-21 15:24 UTC, larrybabb commented
@andreasprlic thank you for working on this. This is a fairly important issue for vrs-Python and the various datasets we are trying to transform from hgvs to vrs. Do you have any sense of when this work will be completed or if it could be handed off to another developer efficiently? No pressure but any information will assist our planning.

2024-02-21 16:05 UTC, andreasprlic commented
@larrybabb Thanks for calling this out. So far we have been treating this one as a "nice to have", not a "must have". 

At this point I believe g_to_c for imprecise events is working. Right now I am looking into the other direction, c_to_g, which will require some "grammar" modifications in how to parse the hgvs-strings. Perhaps it is best if I push what I got so far up, then somebody else who has worked on the parser previously could try to get imprecise hgvs_c parsing to work? @theferrit32 perhaps? :-)

2024-02-21 16:13 UTC, andreasprlic commented
I  pushed my current version of the code.

Note: 
- unit tests for imprecise g_to_c are passing. 
- unit test for partially precise g_to_c is passing too.
- not passing yet: imprecise c_to_g.

2024-02-24 07:21 UTC, andreasprlic commented
@larrybabb for your use case, do you need the support in the direction `g_to_c`, or do you also need `c_to_g`?  I do wonder if the vast majority of use cases are addressed by this PR as it is, and the missing parsing of imprecise c_to_g would be just useful for rare edge cases (and could be done via a future PR).

2024-03-04 16:43 UTC, larrybabb commented
@andreasprlic at this point in time I do not need either the `g_to_c` or the `c_to_g` support. But if I look ahead a bit I think I might like to have the `g_to_c` support down the road.  I do not foresee needing the `c_to_g` on these ambiguous endpoints.

2024-03-11 15:36 UTC, reece commented on src/hgvs/_data/hgvs.pymeta
> +g_interval = uncertain_g_interval:iv | ('(' def_g_interval:iv ')' -> iv._set_uncertain()) | def_g_interval
I'm confused by this. The second alternative parse (with parentheses) is for an uncertain g_interval.

2024-03-13 02:34 UTC, reece requested changes
@andreasprlic @theferrit32 @larrybabb: I figured out my discomfort with the changes in around hgvs.pymeta:125. At the very least, I'd like to discuss this further because I think the current change breaks important parity across variant types.

We currently have coordinates like:
- `5` (`pos` in the grammar)
- `5_5` (`def_x_interval`)
- `(5_5)` (`def_x_interval` with Interval.uncertain = True)

And now we're adding `(5_5)_(5_5)` for genomic sequences only. I think there are two problems with this. 1) We should have parallel constructs for other variant types, 2) `uncertain_g_interval` is a confusing name (to me) because it can be confused with the `(5_5)` form above.

It seems to me that we should be able to refactor this into atomic positions (as is) and a single interval with starts and ends that can be either positions or, now also intervals.

I haven't thought this through fully, but I think this could be implemented by creating a `g_pos_or_interval` rule, then using that in line 132 in lieu of the g_pos:start and :end.

Thanks for your patience. I'm not trying to drive you crazy, but the parity of these rules is part of what makes the hgvs package useful in structuring HGVS variant descriptions, so I'm reluctant to toss this parity across rules without a compelling reason.

2024-09-09 17:58 UTC, reece commented
Per collective coding  meeting discussion on 2024-09-09, here's the path forward:

- Rework grammar changes to preserve analogous grammar across sequence types for def_g_interval, etc.
- Update g-to-c projections to support transformations like those shown in https://github.com/biocommons/hgvs/issues/225#issuecomment-1661318086 
- Ensure tests for each of these

2025-01-21 02:40 UTC, andreasprlic commented
I updated this PR with the following fixes:
- small parser improvement with uncertain_g_interval| def_g_interval
- incorporated unit tests for examples provided in #225 
- The test also demonstrates how the current behavior for imprecise ranges works. During g_to_c we lose the outer-confidence interval, and only maintain the inner confidence interval.

2025-01-21 03:27 UTC, andreasprlic commented
Note:  some of the provided c. examples in #225 are most likely not valid hgvs: e.g. I think this is not valid: `NM_000304.3:c.-34-?_*1140dup1657`. In the current form of this PR, after g_to_c this becomes: `NM_000304.3:c.(?_-34)_(*1140_?)dup'.

2025-03-24 13:39 UTC, reece reviewed
It seems to me that this code still isn't quite ready, or we need to be clearer about the end goal.

I'm mostly over the minor issues I had with grammar changes. (But see comments.)

The bigger issue is that I think we haven't actually solved #225 (or #331). Should we narrow the goal for this PR? @andreasprlic made relevant comments in the discussion thread as well.

2025-03-24 13:39 UTC, reece commented on src/hgvs/_data/hgvs.pymeta
> +uncertain_g_interval = '(' def_g_interval:ivl_start ')' '_' '(' def_g_interval:ivl_end ')' -> hgvs.location.Interval(start=ivl_start._set_uncertain(), end=ivl_end._set_uncertain())
Minor: "iv" is used elsewhere; please keep for consistency

2025-03-24 13:39 UTC, reece commented on src/hgvs/_data/hgvs.pymeta
> +def_g_interval = (g_pos:start '_' g_pos:end -> hgvs.location.Interval(start,end)) | (g_pos:start -> hgvs.location.Interval(start,None))
I like consistency across parallel ideas. It seems to me that we should either decided to deepcopy in the grammar or not, and do it only one way.

What led to changing from the current pattern? (I'm not saying that one is better than the other, but consistency is easier to understand.)

2025-03-24 13:39 UTC, reece commented on src/hgvs/_data/hgvs.pymeta
> +g_interval = uncertain_g_interval:iv |  def_g_interval
To (mostly) preserve the current structure, how about this?

```
g_interval = def_g_interval | imprecise_g_intervals | '(' def_g_interval:iv ')' -> iv._set_uncertain()
```

I think that will make the parallelism between rules easier to follow. (And ditto for c_interval)

2025-03-24 16:09 UTC, andreasprlic commented on tests/test_hgvs_sequencevariant.py
> +
@reece here are the unit tests for #225

2025-04-14 16:45 UTC, reece commented
> Note: some of the provided c. examples in #225 are most likely not valid hgvs: e.g. I think this is not valid: `NM_000304.3:c.-34-?_*1140dup1657`. In the current form of this PR, after g_to_c this becomes: `NM_000304.3:c.(?_-34)_(*1140_?)dup`.

Clinvar genomic  NC_000017.10:g.(?_15133094)_(15164078_?)dup
hgvs:            NM_000304.3                 :c. (?_-34)_(*1140_?)  dup
ClinVar has: NM_000304.3(PMP22)  :c. -34-? _ *1140        dup1657

>>> v = parse("NM_000304.3(PMP22):c.-34-?_*1140dup1657")
HGVSParseError: NM_000304.3(PMP22):c.-34-?_*1140dup1657: char 25: expected a digit

-34-? is not be parsed by hgvs currently because `offset = snum | (-> 0)` (hgvs.pymeta:202)

from tests in #225, clinvar [251062](https://www.ncbi.nlm.nih.gov/clinvar/variation/251062/)
clinvar g                "NC_000019.9:g.(11211022_11213339)_(11217364_11218067)dup",
clinvar c                "NM_000527.5:c.(190+1_191-1)_(817+1_818-1)dup",
hgvs g                "NC_000019.9:g.(?_11213339)_(11217364_?)dup",
hgvs c                "NM_000527.5:c.(?_191-1)_(817+1_?)dup",

On current #699 branch:
>>> var_g1 = parse("NC_000019.9:g.(11211022_11213339)_(11217364_11218067)dup")
>>> var_g1
SequenceVariant(ac=NC_000019.9, type=g, posedit=(11211022_11213339)_(11217364_11218067)dup, gene=None)
>>> var_c1 = am38.g_to_c(var_g1, "NM_000527.5")
>>> var_c1
SequenceVariant(ac=NM_000527.5, type=c, posedit=(?_191-1)_(817+1_?)dup, gene=None)
>>> var_g2 = am38.c_to_g(var_c1)
Traceback (most recent call last):
  Cell In[16], line 1
    var_g2 = am38.c_to_g(var_c1)
  File ~/projects/biocommons/hgvs/src/hgvs/assemblymapper.py:131 in c_to_g
    return self._maybe_normalize(var_out)
  File ~/projects/biocommons/hgvs/src/hgvs/assemblymapper.py:265 in _maybe_normalize
    return self._norm.normalize(var)
  File ~/projects/biocommons/hgvs/src/hgvs/normalizer.py:119 in normalize
    if var.posedit.pos.start.base < 0 or not is_valid_pos(var.ac, var.posedit.pos.end.base):
AttributeError: 'Interval' object has no attribute 'base'


Action items:
- Retain precision of inner and outer boundaries in g_to_c and c_to_g; see example above
- Add support for ? in offset; consider putting in separate issue
- 

                          (190,None)
                        (190+1,None)
         (190+1       _        191-1)
(190+1 _ 191-1) _ (817+1 _ 818-1)

2025-04-15 04:01 UTC, reece commented
@andreasprlic @theferrit32 I did a bunch of surgery on project config diffs between main and this branch. They're now in sync. Tests pass, including on github (i.e., the cache is intact)

Please destroy your venv and rebuild with `make devready` to test.

2025-09-02 00:03 UTC, davmlaw commented
It would be good if you could summarise the current state of things and what needs to be done.

From my quick skim - I'm worried about the silent conversion between types eg g_to_n. The HGVS spec doesn't list how conversions should be done, so we are on our own.

In  ```g_to_n``` - comment is "in case of uncertain ranges, we fall back to the inner (more confident) interval"

This is a valid choice, but I argue it's not the only one.

I would argue:

* We can't convert things silently - the only possible default is to return "p.?" or "c.?"
* We should offer a SequenceVariant convenience method to return a new SequenceVariant object representing uncertain inner interval, so clients can call g_to_n with that explicitly
* We could offer an option in mapper to do this (eg ```uncertain_conversion='inner'``` but better name than I can think of now) which would do your current behavior

2025-09-04 12:34 UTC, anju24 commented
I tested this example. It now works after Andreas [PR](https://github.com/biocommons/hgvs/pull/773) was merged. 
```
In [5]: var_g1 = parse("NC_000019.9:g.(11211022_11213339)_(11217364_11218067)dup")

In [6]: var_g1
Out[6]: SequenceVariant(ac=NC_000019.9, type=g, posedit=(11211022_11213339)_(11217364_11218067)dup, gene=None)

In [7]: var_c1 = am38.g_to_c(var_g1, "NM_000527.5")

In [8]: var_c1
Out[8]: SequenceVariant(ac=NM_000527.5, type=c, posedit=(190+1_191-1)_(817+1_818-1)dup, gene=None)

In [9]: var_g2 = am38.c_to_g(var_c1)

In [10]: var_g2
Out[10]: SequenceVariant(ac=NC_000019.10, type=g, posedit=(11100346_11102663)_(11106688_11107391)dup, gene=None)

In [11]: var_g2 = am37.c_to_g(var_c1)

In [12]: var_g2
Out[12]: SequenceVariant(ac=NC_000019.9, type=g, posedit=(11211022_11213339)_(11217364_11218067)dup, gene=None)

```

2025-09-05 14:32 UTC, andreasprlic commented on src/hgvs/alignmentmapper.py
> +                None if x == -1 or x >= MAX_CHR_SIZE else x for x in all_positions
change this to Math.Inf ?

2025-09-05 14:32 UTC, andreasprlic commented on src/hgvs/alignmentmapper.py
> +                None if x == -1 or x >= MAX_CHR_SIZE else x for x in all_positions
If that does not work use 9999999...

2025-09-05 14:41 UTC, andreasprlic commented on src/hgvs/alignmentmapper.py
> +    def _transform_two_positions_for_reverse_strand(self, pos1, pos2, offset1, offset2):
take this out, no longer needed it seems.

2025-09-05 14:50 UTC, andreasprlic commented on src/hgvs/location.py
> +        if lhs.base is None or rhs.base is None:
test: if left is None -> True, if right is None ->False

2025-09-05 15:10 UTC, andreasprlic commented on src/hgvs/utils/position.py
> +
add docstring that if no outer base, we use inner confidence base

2025-09-05 15:11 UTC, andreasprlic commented on src/hgvs/utils/position.py
> +
add a ticket to add a "strict" mode here which would return Null if there is no outer base.

2025-09-07 18:03 UTC, merged