Fix ins or dups where splice region is preserved
biocommons/hgvs pull request #719
Opened 2024-01-23 19:25 UTC by b0d0nne11

Fixes #714.

Fixes ins or dup variants spanning the intron/exon or exon/intron boundary where the splice site & region remain completely intact.

2024-02-07 14:15 UTC, b0d0nne11 commented
We found some examples of duplications where the original logic here didn't shift the variant far enough to to get the expected result. It turned out that for these variants it's not possible to write the shifted version as a duplication since in a duplication the alt will always follow the ref. I've added some logic to rewrite these shifted variants as insertions before attempting to map them back to `var_p`s and added tests to include these cases.

2024-02-07 14:57 UTC, gostachowiak commented
High-level explanation of this pull request: 
- HGVS nomenclature has the 3' shifting rule.  so all cdots and pdots are shifted to the right
- However, 3' shifting is arbitrary and a necessary evil for nomenclature purposes.  But biology doesn't care about the 3' shifting rule
- Consider an example:  positive strand gene, first 8 bases of the intron is duplicated
- cdot would be +1_+8dup
- currently no pdot would be calculated because both positions have an offset
- but now consider the biology-- after the duplication, there are 2 splice sites on the left side of the intron.  Which is more likely to be used for splicing? 
- We obviously can't know for sure, but it seems to me that the most logical assumption is that it will use the "inner" splice site for splicing, leaving the extra inserted material within the coding sequence, resulting in a frameshift pdot.  Why is this the best assumption? 
-- When that splice site is used, the entire intronic sequence is totally intact
-- Seems "safer" to calculate a pdot for this to rescue the variant-- otherwise downstream applications will most likely be filtering out this variant because it's an insertion after the 8th position in the intron
- To handle this type of situation in the most general way possible, this is the approach: 
-- calculate pdot the normal way.  
-- if empty, shift the cdot in the REVERSE direction, and calculate the pdot again.  if you get a result, use it
-- basically, if you can get a pdot with either forward or reverse shifting, that means the entire intron is intact and we should bring in the pdot
- note that the 3' shifting rule is still respected both for the cdot and pdot nomenclature
-- reverse shifting is only used as a tool when calculating pdot from cdot, which does not violate HGVS nomenclature
-

2024-02-08 12:16 UTC, gostachowiak commented
I also wanted to mention that we discovered this because some fraction of FLT3 ITDs currently get missed when using the hgvs package (including one added to the unit tests).  So it is a high impact issue.

2024-04-12 14:06 UTC, b0d0nne11 commented
Commenting to remove the stale label...

2024-04-12 14:07 UTC, b0d0nne11 commented
@reece or @ahwagner can you remove the stale label here? We would still like to get this merged is possible. Thanks!

2024-05-24 16:24 UTC, b0d0nne11 commented
We found a case where trying to map the shifted variant causes an `HGVSInvalidVariantError`. I've added logic to handle this and a test case. The variant is `NM_182758.2:c.2953-31_2953-26dup`. As part of the shifting procedure, mapping this to the `g` type yielded an unexpected transformation to `NC_000015.9:g.53815545_53815550delinsC` that caused problems with later steps. I'm simply handling the error here since we don't want to consider invalid variants.

2024-05-24 16:24 UTC, b0d0nne11 commented
Also rebased on main

2024-09-14 23:13 UTC, b0d0nne11 commented
Made a few non-functional edits:
- Rebased on main
- Moved tests to an isolated test file
- Squashed some commits

2025-01-02 18:55 UTC, ahwagner commented
@b0d0nne11 is this PR ready for review?

2025-01-14 16:02 UTC, b0d0nne11 commented
Hi @ahwagner, I've been focusing on https://github.com/biocommons/hgvs/pull/748 recently. I think it would be better to get that merged first and then circle back around to this. We definitely still want to get this merged but I think some of the decisions we make there might affect this PR also.

2025-03-10 12:51 UTC, korikuzma reviewed
@b0d0nne11 said they're waiting until #718 is complete. Re-request review once ready.

2025-06-02 18:45 UTC, b0d0nne11 commented
Now that https://github.com/biocommons/hgvs/pull/748 has been merged I'm going to reengage on this PR. I'll let you know when I'm ready for a review or if I have any questions. There is a little refactoring I want to do here first.

2025-06-13 12:37 UTC, b0d0nne11 commented
@korikuzma @ahwagner I think this is ready for a look now. I made a couple of changes beyond just refactoring. I added a configuration parameter to control whether to shift these variants into the exon or the intron. I also added flags to `posedit` to show that the variant is either on the boundary or was shifted. This was requested by one of our clients since it's difficult to tell which variants where shifted after the fact. I wasn't sure that `posedit` was the correct place to put those. I think a case could be made to put them on the `var` or `pos` object instead. I would be happy to move them if you prefer.

2025-06-26 21:16 UTC, b0d0nne11 commented
After some internal discussions I've expanded on this just a bit:
- Added another flag on the result, `shifts_into_exon_and_intron`, to indicate that the variant can be logically shifted between the intron and exon regardless of whether or not that influenced the final result. This can happen if the default HGVS notation would put it into the preferred region. This was another client ask related to the first flag we added. They would like to manually review any variants that fit this pattern and it's difficult to identify them after the fact.
- Since adding `shifts_into_exon_and_intron` required `alt_ac` to be passed into `VariantMapper.c_to_p` in a lot more cases I added a configuration parameter `mapping.shift_over_boundary` to enable or disable the shifting logic. It is disabled by default. This is to avoid breaking existing code and tests.
- Changed the boolean configuration parameter `mapping.shift_over_boundary_is_intronic` to an enum `mapping.shift_over_boundary_preference` with the values `DEFAULT`, `INTRON`, and `EXON`. `DEFAULT` keeps the result from the HGVS notation rules while `INTRON` and `EXON` prefer those regions.

2025-09-04 19:26 UTC, b0d0nne11 commented
Hi @korikuzma @ahwagner et all, I've removed the flags on sequence variants that I added previously as we found a way to handle this in the logic on our end. I've also rebased on main so clear up any conflicts. I think this is ready for a review when you guys have time. Thanks!

2025-10-01 19:06 UTC, b0d0nne11 commented
Hi again @korikuzma @ahwagner @reece, can I get the stale label removed here? We would still like to get this merged if possible. Also if you have any feedback that would be great. Thanks!

2025-10-01 20:44 UTC, reece commented
Hi @b0d0nne11 - I removed the stale label.

I noticed that there are conflicts with main. We'll need to resolve those in order to review. 

I'm going to be without a computer for a week (😱) but I'll take a look when I return.

2025-10-03 20:35 UTC, b0d0nne11 commented
Hey @reece, thanks! I rebased on master and took care of the merge conflicts. I'll also be out next week so no rush. Whenever you have time would be great.

2025-10-13 13:42 UTC, b0d0nne11 commented
Hi @reece, looks like this got marked stale again. Can you take that off?

2025-10-27 18:30 UTC, reece requested changes
@b0d0nne11- This is a great contribution! Thank you! I especially like the shift functions to explore alternative representations. And I appreciate your care in enabling users to opt into new behavior without impinging on existing functionality.

We're working toward a 2.0 release in December. I'd love to include this feature.

2025-10-27 18:30 UTC, reece commented on src/hgvs/_data/defaults.ini
> +shift_over_boundary = False
@b0d0nne11: Would you please add a short comment above each of these describing what they do? Also note that False + DEFAULT correspond to hgvs 1.x code behavior and the team's interpretation of HGVS Nomenclature.

2025-10-27 18:30 UTC, reece commented on src/hgvs/utils/altseqbuilder.py
> +    def get_variant_region(self):
The complexity of these cases warrants explicit tests. Would you please implement those? I *think* that it might be enough to roll these cases into the `cases` block of `test_714.py` with an explicit call to `get_variant_region()`.

2025-10-27 18:30 UTC, reece commented on tests/data/gcp/real.tsv
> -ID00052	NC_000010.10:g.89685314dupT	NM_000314.4:c.209dupT	NP_000305.3:p.?
Please comment why these tests were removed. It scares me to remove tests because it implies that the tests were wrong and therefore that the code was passing something that it should have. These particular tests were contributed by some extremely experienced clinical geneticists at Invitae (in ~2015). 

To be clear, we should remove them if they're wrong. I just want to know that rationale explicitly. And, while I can see the two deleted tests might be questionable, the rationale that I would use would implicate most or all of these p.? tests, not just these two.

2025-10-27 18:30 UTC, reece commented on src/hgvs/variantmapper.py
> +    def _var_c_shifts(self, var_c, alt_ac, alt_aln_method):
Please add tests for the _var_c_shifts and _var_g_shifts methods.

2025-10-29 04:35 UTC, andreasprlic commented on src/hgvs/variantmapper.py
> +        normalizer = hgvs.normalizer.Normalizer(
rather than creating this here on every call of `_var_g_shift_with_rewrite`, should we move this (perhaps even as an optional argument) into the `VariantMapper.__init__()`?

2025-10-29 04:35 UTC, andreasprlic commented on src/hgvs/variantmapper.py
> +        var_g = normalizer.normalize(var_g)
I did not test this, but I suspect that calling normalize() is slow. What would happen if we would not call the normalizer here?

2025-10-29 04:39 UTC, andreasprlic commented
Overall I am very happy with this PR, and I would like to approve it, once Reece's comments have been addressed (mostly about testing). This is an improvement that shows great attention to detail and that solves an important edge case in a way that can be configured (and the default is compliant with HGVS nomenclature). Thanks for putting in all this effort! This is greatly appreciated.

2026-03-22 06:00 UTC, andreasprlic commented
I am interested in getting this PR fixed and merged. As such I took a stab at it here:
#821

2026-08-07 22:56 UTC, reece commented
Closing as superseded by #821, which arrived at the same fix independently while resolving conflicts against `main`.

Evidence:
- `tests/issues/test_714.py` (the test encoding this fix's expected behavior) is byte-identical between the two PR branches.
- `tests/support/mock_input_source.py` is also byte-identical.
- `src/hgvs/_data/defaults.ini` and `src/hgvs/enums.py` (the `ShiftOverBoundaryPreference` enum and its config default) are identical between both branches.
- #821's own history contains an explicit merge commit stating it merged `ShiftOverBoundaryPreference` and `HGVSInvalidIntervalError` imports "from PR #719."
- The one apparent gap — this branch's `AssemblyMapper._var_c_shifts()` override and its constructor params — isn't missing functionality in #821, just a different architecture: #821 resolves `alt_ac` from `tx_ac` once at the top-level `AssemblyMapper.c_to_g`/`t_to_g`/etc. methods and threads it down to `VariantMapper._var_c_shifts` directly, rather than re-resolving it inside a per-shift override.

No changes from this branch are missing in #821.

2026-08-07 22:56 UTC, closed without merging